language:
  python
python:
 - "3.8"
install:
 - pip install -U pip
 - pip install -r requirements.txt
 - pip install coverage
 - pip install codecov
git:
  depth: 50
jobs:
  include:
  - name: "project-1"
    python: "3.8"
script:
  - flake8 --ignore=E501,E402,E722
  - coverage run -m pytest -q test/
after_success:
  - bash <(curl -s https://codecov.io/bash) -t dbd73cb8-9de3-470f-8868-c3f7b1975f12
