language: 
  python
python:
- "3.8"
install:
- pip install -U pip
- pip install -r requirements.txt
- pip install coverage
- pip install codecov
- pip install pytest
- pip install pytest-cov==2.7.1

script:
- cd test
- pytest
- pytest --cov-report term --cov=investpy test/
